server:
  port: 4442

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springfox:
  documentation:
    swaggerUi:
      baseUrl: /api/doc

spring:
  profiles:
    active: native
  application:
    name: market-gateway
  cloud:
    gateway:
      global-cors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true

