server:
  port: 8888

spring:
  application:
    name: market-documentation-service

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

swagger:
  config:
    refreshRate: 5000