server:
  port: 8088

eureka:
  instance:
    appname: market-storage
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

springfox:
  documentation:
    swaggerUi:
      baseUrl: /api/doc

spring:
  profiles:
    active: native
  application:
    name: market-storage
  datasource:
    url: jdbc:h2:mem:testdb
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
      properties:
        hibernate.format_sql: true