--liquibase formatted sql
--changeset Savchenko:db-init
CREATE TABLE role
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    authority VARCHAR(255) UNIQUE                     NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id)
);
CREATE TABLE account
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    last_name     VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    role          VARCHAR(255)                            NOT NULL,
    is_blocked    BOOLEAN,
    CONSTRAINT pk_account PRIMARY KEY (id)
);

ALTER TABLE account
    ADD CONSTRAINT uc_2a01e8b686318ad71bb30dbd9 UNIQUE (email);

ALTER TABLE account
    ADD CONSTRAINT FK_ACCOUNT_ON_ROLE FOREIGN KEY (role) REFERENCES role (authority);
CREATE TABLE password_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(255),
    account_id  BIGINT                                  NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_password_tokens PRIMARY KEY (id)
);

ALTER TABLE password_tokens
    ADD CONSTRAINT FK_PASSWORD_TOKENS_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (id);