FROM openjdk:latest
ENV PROJECT_ROOT "C:\Users"
WORKDIR $PROJECT_ROOT
COPY ./market-statistics-service-0.0.1-SNAPSHOT.jar market-statistics-service-0.0.1-SNAPSHOT.jar
CMD java -jar market-statistics-service-0.0.1-SNAPSHOT.jar

