version: '3.1'

volumes:
  db-mongo:
  db-postgre:
  zookeeper:
  kafka:

networks:
  market-net:
    name: market-net
    driver: bridge

services:

  # services for database

  db-adminer:
    container_name: db-adminer
    image: adminer:latest
    build:
      context: ../docker-script/adminer
      dockerfile: Dockerfile
    restart: always
    environment:
      ADMINER_DESIGN: 'pappu687'
      MONGO_HOST: mongo-server
      POSTRGRE_HOST: postgre-server
    ports:
      - 80:8080
    networks:
      - market-net
    links:
      - db-mongo:mongo-server
      - db-postgre:postgre-server

  db-adminer-mongo:
    container_name: db-adminer-mongo
    image: mongo-express
    restart: always
    depends_on:
      - db-mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@db-mongo:27017/
    ports:
      - 81:8081
    networks:
      - market-net

  db-mongo:
    container_name: db-mongo
    image: mongo
    restart: always
    command: --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: market
    ports:
      - 27017:27017
    networks:
      - market-net
    volumes:
      - db-mongo:/data/db
      - db-mongo:/data/configdb

  db-postgre:
    container_name: db-postgre
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: market
    ports:
      - 5432:5432
    networks:
      - market-net
    volumes:
      - db-postgre:/var/lib/postgresql/data

  # services for my own services

  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    restart: "no"
    ports:
      - 2181:2181
    networks:
      - market-net

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    restart: "no"
    networks:
      - market-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    #      KAFKA_BROKER_ID: 1
    #      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    volumes:
      - kafka:/etc/kafka/secrets
      - kafka:/var/lib/kafka/data